# Generated by Django 2.2.16 on 2022-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220723_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='admin', max_length=5, verbose_name='Роль пользователя'),
        ),
    ]
