version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  # Примеры наполнения файла .env представлены в README и .env.template

  web:
    image: vinsteam/backend-food:v1.2
    # build:
    #   context: ../backend
    restart: always
    volumes:
      - backend_static:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: vinsteam/front-food:v1.1
    restart: always
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend


volumes:
  db:
  backend_static:
  media_value: